// <auto-generated />
using System;
using GraphQLExample.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQLExample.Server.Migrations
{
    [DbContext(typeof(LotusContext))]
    partial class LotusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("GraphQLExample.Shared.Lotus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lotussen");
                });

            modelBuilder.Entity("GraphQLExample.Shared.Opdracht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AantalUur")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BeginTijd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumAanvraag")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Opdrachten");
                });
#pragma warning restore 612, 618
        }
    }
}
